---
layoout: post
title:  "Golang에서의 Error와 그 처리"
crawlertitle: post_golang_error
date:   2020-12-26 14:37:50 +0900
categories: golang
summary: "Golang에서의 Error와 그 처리에 대한 설명입니다."
---  
###### 1. Error  
&nbsp;**1.1. Error**  
&nbsp;&nbsp;Error 처리를 위해 Golang에 내장된 Type입니다. error 조건을 나타내기 위한 기본 Interface로 정의되며 Error가 없는 경우 기본 nil입니다. Package **errors**에는 error를 조작하기 위한 함수가 정의되어 있어 다양하게 사용할 수 있습니다.   

- Golang 내장 error 정의
~~~go
type error interface {
	Error() string
}
~~~  

- 사용 예
~~~go
func main() {
	var err error
	_, err = os.Stat("info.txt")
	if os.IsNotExist(err) {
		err = fmt.Errorf("Not exsist 'info.txt")
	} else {
		err = os.Remove("info.txt")
	}
}
~~~

&nbsp;**1.2. Runtime Error**  
&nbsp;&nbsp;프로그램 실행 중 발생하는 error는 interface type으로 구현, 정의된 runtime.Error 값과 함께 내장된 panic 함수와 동일한 런타임 panic 함수를 발생시킵니다. 이 Type은 미리 선언된 interface type인 error를 충족하며 고유한 런타임 error 조건을 나타내는 정확한 error 값은 지정되지 않습니다. 아래는 runtime package에 포함된 Error의 정의입니다.  

~~~go
package runtime

type Error interface {
	error
}
~~~  

###### 2. Panic  
&nbsp;내장된 함수로 런타임 Panic과 프로그램에 정의된 error 상태를 보고할 수 있습니다.  
~~~go
func panic(interface{})
~~~

&nbsp;함수가 실행하는 동안 Panic이나 런타임 Panic이 명시적으로 호출되면 해당 함수의 실행을 종료합니다. 그리고 해당 함수가 호출한 모든 지연된 함수가 실행되고 실행 중인 goroutine의 최상위 함수에 의해 지연된 모든 함수가 실행됩니다. 이 때 프로그램이 종료하고 Panic에 대한 인수 값을 포함한 error 상태를 보고합니다. 이 종료 시퀀스를 Panicking이라고 합니다.  

~~~go
// File을 삭제하지 못하면 error 발생
func removeFile(filePath string) {
	var err error
	_, err = os.Stat(removeFile)
	if os.IsNotExist(err) {
		err = fmt.Errorf("Not exsist file")
	} else {
		err = os.Remove(removeFile)
	}

	if err != nil {
		panic(err)
	}
}
~~~  

###### 3. Recover  
&nbsp;내장된 함수로 런타임 Panic과 프로그램에 정의된 error 상태를 처리할 수 있습니다. 프로그램에서 Panicking goroutine의 동작을 관리할 수 있습니다.  
~~~go
func recover() interface{}
~~~

&nbsp;다음 조건 중 하나라도 충족되면 recover의 결과 값은 nil입니다.  
- Panic의 인자가 nil입니다.
- goroutine은 Panicking이 아닙니다.
- recover에서 지연된 함수를 직접 호출하지 않습니다.

&nbsp;recover를 호출하는 함수(funcRecover)와 해당 함수를 지연 호출하는 함수(funcCaller)가 있을 때, 다른 함수를 지연 호출하는 함수(funcCaller)가 실행되는 동안 동일한 goroutine 함수에서 panic이 발생한다고 가정합니다. recover를 호출하는 지연 함수(funcRecover)가 호출될 때 해당 함수에서 호출한 recover의 결과값은 panic 호출시 전달됩니다. 만약 recover를 호출하는 지연 함수(funcRecover)가 정상적으로 종료하면 새로운 panic의 시작 없이 Panicking sequence가 중지됩니다. 그리고 해당 함수를 지연 호출한 함수(funcCaller)와 panic 사이에서 호출되는 함수의 상태는 삭제되고 정상적으로 실행이 재개됩니다. recover를 호출하는 지연 함수(funcRecover)가 실행되기 전에 해당 함수를 지연 호출한 함수(funcCaller)에 의해 다른 지연된 모든 함수가 실행되고 반환되어 관련 함수의 실행은 종료됩니다.  

~~~go
func main() {
	// error 처리
	defer func() {
		resultValue := recover()
		if resultValue != nil {
			fmt.Printf("[panic] %v", resultValue)
		}
	}()

	var err error
	_, err = os.Stat("info.txt")
	if os.IsNotExist(err) {
		err = fmt.Errorf("Not exsist 'info.txt")
	} else {
		err = os.Remove("info.txt")
	}

	if err != nil {
		panic(err)
	}
}
~~~  

위의 예는 main에서 호출하는 함수에 대해서 모든 panic 처리를 하지만 아래처럼 각 함수에서 panic이 발생되지 않도록 처리할 수도 있습니다.  
~~~go
func functionWithoutPanic(targetFunc func()) {
	defer func() {
		if resultValue := recover(); resultValue != nil {
			fmt.Printf("panic : %v\n", resultValue)
		}
	}()

	targetFunc()
}
~~~

###### [참고]  
- [Golang의 Error 설명](https://golang.org/ref/spec#Errors)
- [error package](https://golang.org/pkg/errors)
- [Golang에서 Panic 처리](https://golang.org/ref/spec#Handling_panics)
- [Golang에서 Runtime Panic 처리](https://golang.org/ref/spec#Run_time_panics)